Requirement already satisfied: pandas in /home/lostm/.local/lib/python3.8/site-packages (1.4.3)
Requirement already satisfied: numpy>=1.18.5; platform_machine != "aarch64" and platform_machine != "arm64" and python_version < "3.10" in /home/lostm/.local/lib/python3.8/site-packages (from pandas) (1.23.2)
Requirement already satisfied: pytz>=2020.1 in /home/lostm/.local/lib/python3.8/site-packages (from pandas) (2022.2.1)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.1->pandas) (1.14.0)
Installing collected packages: python-dateutil
Successfully installed python-dateutil-2.8.2
